import Layout from '@/component/layout/Layout'
import AboutMain from '@/component/main/AboutMain'
import Head from 'next/head'
import React from 'react'

const about = () => {
  return (
    <>
        <Head>
        <title>Beamen Tech LLC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="assets/img/favicon.png" type="image/x-icon"/>
        </Head>
        <>
            <Layout>
              <AboutMain/>
            </Layout>
        </>
    </>
  )
}

export default about