import Layout from '@/component/layout/Layout'
import BlogDetailMain from '@/component/main/BlogDetailMain'
import Head from 'next/head'
import React from 'react'

const blogDetails = () => {
  return (
    <>
        <Head>
            <title>Nafiab - Blog Details</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="shortcut icon" href="assets/img/favicon.png" type="image/x-icon"/>
        </Head> 
        <Layout>
            <BlogDetailMain/>
        </Layout>
    </>
  )
}

export default blogDetails