import BreadcrumbSection from '@/component/breadcrumb/BreadcrumbSection'
import Layout from '@/component/layout/Layout'
import Head from 'next/head'
import React from 'react'

const cableTv = () => {
    return (
        <>
            <Head>
                <title>Beamen Tech LLC</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="shortcut icon" href="assets/img/favicon.png" type="image/x-icon" />
            </Head>
            <>
                <Layout>
                    <main>
                        <BreadcrumbSection title={"Disclaimer "} />
                        <div style={{ width: "60%", margin: "auto", textAlign: "center", padding: '30px 0' }}>
                            <h1 >  <b>Disclaimer</b></h1>
                            <p style={{ fontSize: '20px' }}>Disclaimer
                                Beamen Tech LLC is not responsible for any content, code, or any other inaccuracies. Beamen Tech LLC makes no guarantees. In no event shall Beamen Tech LLC be liable for any special, direct, indirect, consequential, or incidental damages or any damages whether in an action of contract, negligence or other tort arising out of or in connection with the use of the Service or the contents of the Service. Beamen Tech LLC reserves the right to make additions, deletions, or modification to the contents of the Service at any time without prior notice.

                                The Beamen Tech LLC Service and its content are provided "as is" and "as available" without any warranty or representations of any kind, either express or implied. Beamen Tech LLC is a distributor and not a publisher of content provided by third parties; as such, Beamen Tech LLC exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability, or currency of any information, content, services, or merchandise provided or accessible through the Beamen Tech LLC Service. Without limiting the foregoing, Beamen Tech LLC specifically disclaims all warranties and representations in any content transmitted on or in connection with the Beamen Tech LLC Service or on sites that may appear as links on the Beamen Tech LLC Service, or in the products provided as part of or in connection with the Beamen Tech LLC Service, including without limitation any warranties of merchantability, fitness for a particular purpose, or non-infringement of third-party rights. No oral advice or written information given by Beamen Tech LLC, nor its affiliates, employees, officers, directors, agents, or the like shall create a warranty. Pricing and availability information is subject to change without notice. Without limiting the foregoing, Beamen Tech LLC does not warrant that the Beamen Tech LLC Service will be uninterrupted, uncorrupted, timely, or error-free.</p>

                        </div>
                    </main>
                </Layout>
            </>
        </>
    )
}

export default cableTv