import Layout from '@/component/layout/Layout'
import HomePageMain2 from '@/component/main/HomePageMain2'
import Head from 'next/head'
import React from 'react'

const homePage2 = () => {
  return (
    <>
        <Head>
        <title>Nafiab - Home Page 2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="assets/img/favicon.png" type="image/x-icon"/>
        </Head>
        <Layout>
            <HomePageMain2/>
        </Layout>
    </>
  )
}

export default homePage2