import HeaderBanner from '@/component/banner/HeaderBanner'
import FooterSection from '@/component/footer/FooterSection'
import IndexMain from '@/component/main/IndexMain'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Newill Resources LLC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="assets/img/favicon.png" type="image/x-icon"/>
      </Head>
      <>
        <HeaderBanner/>
        <IndexMain/>
        <FooterSection/>
      </>
    </>
  )
}
