import BreadcrumbSection from "@/component/breadcrumb/BreadcrumbSection";
import Layout from "@/component/layout/Layout";
import Head from "next/head";
import React from "react";

const cableTv = () => {
  return (
    <>
      <Head>
        <title>Beamen Tech LLC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="shortcut icon"
          href="assets/img/favicon.png"
          type="image/x-icon"
        />
      </Head>
      <>
        <Layout>
          <main>
            <BreadcrumbSection title={"Refund Policy"} />
            <div
              style={{
                width: "60%",
                margin: "auto",
                textAlign: "center",
                padding: "30px 0",
              }}
            >
              <h1>
                {" "}
                <b>Refund Policy</b>
              </h1>
              <p style={{ fontSize: "20px" }}>
                Rayan Logistics Refund Policy At Rayan Logistics, we strive to
                ensure customer satisfaction with every purchase. If you are not
                completely satisfied with your electronic product, you may be
                eligible for a refund under the following conditions:
                Eligibility for Refund Time Frame: You may request a refund
                within 30 days of the purchase date. Condition: The product must
                be in its original condition, unused, and with all original
                packaging and accessories. Proof of Purchase: A valid proof of
                purchase (receipt or order number) is required for all refund
                requests. Non-Refundable Items Products that are damaged due to
                misuse, neglect, or accidental damage. Items marked as final
                sale or non-returnable at the time of purchase. Software or
                digital products that have been downloaded or activated. Refund
                Process Initiate a Refund: Contact our customer service team via
                email at support@rayanlogistics.com to initiate the refund
                process. Provide your order number and reason for the refund.
                Return Authorization: Our team will provide you with a return
                authorization number and instructions on how to return the
                product. Shipping: You are responsible for the return shipping
                costs. We recommend using a trackable shipping method to ensure
                your return is received. Inspection: Once we receive the
                returned product, it will be inspected to ensure it meets the
                refund eligibility criteria. Processing: If approved, your
                refund will be processed within 7-10 business days. The refund
                will be credited to the original payment method used for the
                purchase. Refund Exceptions Refunds will not be granted for
                products that do not meet the above criteria. Partial refunds
                may be issued at our discretion for products that are returned
                with missing accessories or original packaging. Contact Us For
                any questions or concerns regarding our refund policy, please
                contact our customer service team at support@rayanlogistics.com.
                We are here to assist you. Thank you for shopping with
                RayanÂLogistics!
              </p>
            </div>
          </main>
        </Layout>
      </>
    </>
  );
};

export default cableTv;
