import BreadcrumbSection from '@/component/breadcrumb/BreadcrumbSection'
import Layout from '@/component/layout/Layout'
import Head from 'next/head'
import React from 'react'

const cableTv = () => {
    return (
        <>
            <Head>
                <title>Beamen Tech LLC</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="shortcut icon" href="assets/img/favicon.png" type="image/x-icon" />
            </Head>
            <>
                <Layout>
                    <main>
                        <BreadcrumbSection title={"Terms and Condition"} />
                        <div style={{ width: "60%", margin: "auto", textAlign: "left", padding: '30px 0' }}>
                            <h1 >  <b>Terms and Condition</b></h1>
                            <b >Last Updated on May 9, 2024</b>
                            <br />
                            <b style={{ margin: '30px 0'}}>Use of Our Website</b>

                            <p style={{ fontSize: '20px' }}>You are permitted to use this site for your own purposes to print, download, and share material provided you do not modify any content without our explicit consent. Material on this website may not be republished online or offline without our permission. The copyright and all intellectual property rights of the material on this site are owned by Zolara Tech LLC and may not be reproduced without our prior consent.</p>

                            <b style={{ margin: '30px 0'}}> Visitor Conduct</b>
                            <li style={{ fontSize: '20px' }}> With the exception of personal information (the use of which is covered under our Privacy Policy), any material you send or post to this write shall be considered non-proprietary and not confidential. Unless you advise to the contrary, we remain free to copy, disclose, distribute, incorporate and otherwise use such material for any and all purposes.</li>
                            <li>When using the site, please do not post or send any material for which you have not obtained all necessary consents or that which is discriminatory, obscene, pornographic, defamatory, liable to incite racial hatred, in breach of confidentiality or privacy to or from this site, which may cause annoyance or inconvenience to others, which encourages or constitutes conduct that would be deemed a criminal offense, give rise to a civil liability, or otherwise is contrary to the law of the United States of America.</li>
                            <b style={{ margin: '30px 0'}}>Site Activity
                            </b>
                            <p style={{ fontSize: '20px' }}> We take the utmost care to ensure that this site is available 24/7, 365 days per year. However, websites do sometimes encounter downtime due to server or technical issues. We are not liable if this website is unavailable at any time.</p>
                            <b style={{ margin: '30px 0'}}> Links to and from other Websites</b>
                            <p style={{ fontSize: '20px' }}>In order to provide additional information or services, Zolara Tech LLC may include links to external websites. Clicking on such a link will navigate you away from the Digital Marketing Agencies site. The inclusion of links does not necessarily imply a recommendation, nor does it in any way endorse the views expressed within them. Other site’s Terms and Conditions may differ from our own. When clicking off the Zolara Tech LLC site, we strongly encourage you to visit the other site’s Terms and Conditions to ensure it meets the standards of your own personal preferences.</p>
                            <b style={{ margin: '30px 0'}}> Exclusion of Liability</b>
                            <p style={{ fontSize: '20px' }}>In no event will Zolara Tech LLC be held liable for any loss or damage of information including but not limited to indirect or consequential loss or damage, loss or damage of data, or profits arising out of or in connection with the use of this website. Zolara Tech LLC may not be held liable or responsible in any way for loss or damage that may result to you or a third party as a result of your use of our website.</p>

                            <b style={{ margin: '30px 0'}}> Governing Law</b>
                            <p style={{ fontSize: '20px' }}>These legal Terms and Conditions apply for all issues regarding this website shall be governed by the laws of the United States of America and in the state of New Mexico or the appropriate defending country.</p>

                        </div>
                    </main>
                </Layout>
            </>
        </>
    )
}

export default cableTv

